/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import hollowGltf from "../../assets/hollowCube.gltf";

export function Model(props) {
  const { nodes, materials } = useGLTF(hollowGltf);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        // material={MeshNormalMaterial}
      />
      <meshBasicMaterial color={"red"} />
    </group>
  );
}

useGLTF.preload(hollowGltf);
